name: update deps

on:
  schedule:
    - cron: "0 5 * * 1"

jobs:
  udpate-deps:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      security-events: read

    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - run: pnpm install --no-frozen-lockfile
      - run: pnpm test
      - name: Update dependencies and check security
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm run update
      - run: pnpm install --no-frozen-lockfile
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PR_CREATE_TOKEN }}
          commit-message: chore: update dependencies
          title: "[Codependence]  update dependencies"
          body: |
            ## Dependency updates
            Auto-generated by [codependence][1] using [create-pull-request][2]
            [1]: https://github.com/yowainwright/es-check
            [2]: https://github.com/peter-evans/create-pull-request
          branch: update-dependencies
          labels: codependencies
